coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 100%
        threshold: 10%

ignore:
  - "**/*.pb.go"
  - "**/*.gw.go"
  - "**/*_test.go"
  - "**/testexchange/**"
  - "**/benchmarks/**"
  - "**/.github/**"

fixes:
  - "/injective-core::"

comment:
  layout: "diff"
